
package mx.com.cinepolis.digital.booking.model.ws.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfCiudad;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfComplejo;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfDistribuidora;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfEstado;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfFestival;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfFormato;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfHorariosPelicula;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfHorariosPeliculaHorariosComplejoNokia;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfImagenGenerica;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfMultimedia;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPais;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPelicula;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPromocion;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPromocionMoviles;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfRelacionComplejoPelicula;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfRuta;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfTarifa;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ArrayOfTipoHorarioFiltro;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.Dispositivos;
import mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.Version;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IConsumo", targetNamespace = "http://api.cinepolis.com")
@XmlSeeAlso({
	mx.com.cinepolis.digital.booking.model.ws.com.cinepolis.api.ObjectFactory.class,
	mx.com.cinepolis.digital.booking.model.ws.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
	mx.com.cinepolis.digital.booking.model.ws.org.datacontract.schemas._2004._07.apicinepolis.ObjectFactory.class,
	mx.com.cinepolis.digital.booking.model.ws.com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class
})
public interface IConsumo {


    /**
     * 
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPais
     */
    @WebMethod(operationName = "ObtenerPaises", action = "http://api.cinepolis.com/IConsumo/ObtenerPaises")
    @WebResult(name = "ObtenerPaisesResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPaises", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPaises")
    @ResponseWrapper(localName = "ObtenerPaisesResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPaisesResponse")
    public ArrayOfPais obtenerPaises(
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfCiudad
     */
    @WebMethod(operationName = "ObtenerCiudades", action = "http://api.cinepolis.com/IConsumo/ObtenerCiudades")
    @WebResult(name = "ObtenerCiudadesResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerCiudades", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerCiudades")
    @ResponseWrapper(localName = "ObtenerCiudadesResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerCiudadesResponse")
    public ArrayOfCiudad obtenerCiudades(
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param formato
     * @param idsPaises
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfCiudad
     */
    @WebMethod(operationName = "ObtenerCiudadesPaises", action = "http://api.cinepolis.com/IConsumo/ObtenerCiudadesPaises")
    @WebResult(name = "ObtenerCiudadesPaisesResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerCiudadesPaises", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerCiudadesPaises")
    @ResponseWrapper(localName = "ObtenerCiudadesPaisesResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerCiudadesPaisesResponse")
    public ArrayOfCiudad obtenerCiudadesPaises(
        @WebParam(name = "idsPaises", targetNamespace = "http://api.cinepolis.com")
        String idsPaises,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idPais
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfCiudad
     */
    @WebMethod(operationName = "ObtenerCiudadesPais", action = "http://api.cinepolis.com/IConsumo/ObtenerCiudadesPais")
    @WebResult(name = "ObtenerCiudadesPaisResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerCiudadesPais", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerCiudadesPais")
    @ResponseWrapper(localName = "ObtenerCiudadesPaisResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerCiudadesPaisResponse")
    public ArrayOfCiudad obtenerCiudadesPais(
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        Integer idPais,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idsCiudades
     * @param idsComplejos
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfComplejo
     */
    @WebMethod(operationName = "ObtenerComplejos", action = "http://api.cinepolis.com/IConsumo/ObtenerComplejos")
    @WebResult(name = "ObtenerComplejosResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerComplejos", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerComplejos")
    @ResponseWrapper(localName = "ObtenerComplejosResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerComplejosResponse")
    public ArrayOfComplejo obtenerComplejos(
        @WebParam(name = "idsCiudades", targetNamespace = "http://api.cinepolis.com")
        String idsCiudades,
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idsComplejos
     * @param formato
     * @param idsPaises
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPelicula
     */
    @WebMethod(operationName = "ObtenerPeliculasCartelera", action = "http://api.cinepolis.com/IConsumo/ObtenerPeliculasCartelera")
    @WebResult(name = "ObtenerPeliculasCarteleraResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPeliculasCartelera", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasCartelera")
    @ResponseWrapper(localName = "ObtenerPeliculasCarteleraResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasCarteleraResponse")
    public ArrayOfPelicula obtenerPeliculasCartelera(
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "idsPaises", targetNamespace = "http://api.cinepolis.com")
        String idsPaises,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param dispositivo
     * @param idsComplejos
     * @param formato
     * @param idsPaises
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPelicula
     */
    @WebMethod(operationName = "ObtenerPeliculasCarteleraDispositivo", action = "http://api.cinepolis.com/IConsumo/ObtenerPeliculasCarteleraDispositivo")
    @WebResult(name = "ObtenerPeliculasCarteleraDispositivoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPeliculasCarteleraDispositivo", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasCarteleraDispositivo")
    @ResponseWrapper(localName = "ObtenerPeliculasCarteleraDispositivoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasCarteleraDispositivoResponse")
    public ArrayOfPelicula obtenerPeliculasCarteleraDispositivo(
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "idsPaises", targetNamespace = "http://api.cinepolis.com")
        String idsPaises,
        @WebParam(name = "dispositivo", targetNamespace = "http://api.cinepolis.com")
        Dispositivos dispositivo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idPais
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPelicula
     */
    @WebMethod(operationName = "ObtenerPeliculasEstrenos", action = "http://api.cinepolis.com/IConsumo/ObtenerPeliculasEstrenos")
    @WebResult(name = "ObtenerPeliculasEstrenosResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPeliculasEstrenos", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasEstrenos")
    @ResponseWrapper(localName = "ObtenerPeliculasEstrenosResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasEstrenosResponse")
    public ArrayOfPelicula obtenerPeliculasEstrenos(
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        String idPais,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idPais
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPelicula
     */
    @WebMethod(operationName = "ObtenerPeliculasEstreno", action = "http://api.cinepolis.com/IConsumo/ObtenerPeliculasEstreno")
    @WebResult(name = "ObtenerPeliculasEstrenoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPeliculasEstreno", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasEstreno")
    @ResponseWrapper(localName = "ObtenerPeliculasEstrenoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasEstrenoResponse")
    public ArrayOfPelicula obtenerPeliculasEstreno(
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        String idPais,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idPais
     * @param dispositivo
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPelicula
     */
    @WebMethod(operationName = "ObtenerPeliculasEstenoDispositivo", action = "http://api.cinepolis.com/IConsumo/ObtenerPeliculasEstenoDispositivo")
    @WebResult(name = "ObtenerPeliculasEstenoDispositivoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPeliculasEstenoDispositivo", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasEstenoDispositivo")
    @ResponseWrapper(localName = "ObtenerPeliculasEstenoDispositivoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasEstenoDispositivoResponse")
    public ArrayOfPelicula obtenerPeliculasEstenoDispositivo(
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        String idPais,
        @WebParam(name = "dispositivo", targetNamespace = "http://api.cinepolis.com")
        Dispositivos dispositivo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idPais
     * @param idsComplejos
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPelicula
     */
    @WebMethod(operationName = "ObtenerPeliculasFestivales", action = "http://api.cinepolis.com/IConsumo/ObtenerPeliculasFestivales")
    @WebResult(name = "ObtenerPeliculasFestivalesResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPeliculasFestivales", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasFestivales")
    @ResponseWrapper(localName = "ObtenerPeliculasFestivalesResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasFestivalesResponse")
    public ArrayOfPelicula obtenerPeliculasFestivales(
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        String idPais,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idPais
     * @param dispositivo
     * @param idsComplejos
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPelicula
     */
    @WebMethod(operationName = "ObtenerPeliculasFestivalesDispositivo", action = "http://api.cinepolis.com/IConsumo/ObtenerPeliculasFestivalesDispositivo")
    @WebResult(name = "ObtenerPeliculasFestivalesDispositivoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPeliculasFestivalesDispositivo", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasFestivalesDispositivo")
    @ResponseWrapper(localName = "ObtenerPeliculasFestivalesDispositivoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasFestivalesDispositivoResponse")
    public ArrayOfPelicula obtenerPeliculasFestivalesDispositivo(
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        String idPais,
        @WebParam(name = "dispositivo", targetNamespace = "http://api.cinepolis.com")
        Dispositivos dispositivo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idPais
     * @param formato
     * @param idsVista
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPelicula
     */
    @WebMethod(operationName = "ObtenerPeliculasCarteleraPlasma", action = "http://api.cinepolis.com/IConsumo/ObtenerPeliculasCarteleraPlasma")
    @WebResult(name = "ObtenerPeliculasCarteleraPlasmaResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPeliculasCarteleraPlasma", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasCarteleraPlasma")
    @ResponseWrapper(localName = "ObtenerPeliculasCarteleraPlasmaResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPeliculasCarteleraPlasmaResponse")
    public ArrayOfPelicula obtenerPeliculasCarteleraPlasma(
        @WebParam(name = "idsVista", targetNamespace = "http://api.cinepolis.com")
        String idsVista,
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        String idPais,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idPais
     * @param formato
     * @param idsVista
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPelicula
     */
    @WebMethod(operationName = "ObtenerHistorialPeliculasFacebook", action = "http://api.cinepolis.com/IConsumo/ObtenerHistorialPeliculasFacebook")
    @WebResult(name = "ObtenerHistorialPeliculasFacebookResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerHistorialPeliculasFacebook", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHistorialPeliculasFacebook")
    @ResponseWrapper(localName = "ObtenerHistorialPeliculasFacebookResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHistorialPeliculasFacebookResponse")
    public ArrayOfPelicula obtenerHistorialPeliculasFacebook(
        @WebParam(name = "idsVista", targetNamespace = "http://api.cinepolis.com")
        String idsVista,
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        String idPais,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param formato
     * @param idPelicula
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfFormato
     */
    @WebMethod(operationName = "ObtenerFormatos", action = "http://api.cinepolis.com/IConsumo/ObtenerFormatos")
    @WebResult(name = "ObtenerFormatosResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerFormatos", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerFormatos")
    @ResponseWrapper(localName = "ObtenerFormatosResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerFormatosResponse")
    public ArrayOfFormato obtenerFormatos(
        @WebParam(name = "idPelicula", targetNamespace = "http://api.cinepolis.com")
        Integer idPelicula,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param formato
     * @param idPelicula
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfMultimedia
     */
    @WebMethod(operationName = "ObtenerMultimediaFichaTecnica", action = "http://api.cinepolis.com/IConsumo/ObtenerMultimediaFichaTecnica")
    @WebResult(name = "ObtenerMultimediaFichaTecnicaResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerMultimediaFichaTecnica", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerMultimediaFichaTecnica")
    @ResponseWrapper(localName = "ObtenerMultimediaFichaTecnicaResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerMultimediaFichaTecnicaResponse")
    public ArrayOfMultimedia obtenerMultimediaFichaTecnica(
        @WebParam(name = "idPelicula", targetNamespace = "http://api.cinepolis.com")
        Integer idPelicula,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param dispositivo
     * @param formato
     * @param idPelicula
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfMultimedia
     */
    @WebMethod(operationName = "ObtenerMultimediaFichaTecnicaDispositivo", action = "http://api.cinepolis.com/IConsumo/ObtenerMultimediaFichaTecnicaDispositivo")
    @WebResult(name = "ObtenerMultimediaFichaTecnicaDispositivoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerMultimediaFichaTecnicaDispositivo", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerMultimediaFichaTecnicaDispositivo")
    @ResponseWrapper(localName = "ObtenerMultimediaFichaTecnicaDispositivoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerMultimediaFichaTecnicaDispositivoResponse")
    public ArrayOfMultimedia obtenerMultimediaFichaTecnicaDispositivo(
        @WebParam(name = "idPelicula", targetNamespace = "http://api.cinepolis.com")
        Integer idPelicula,
        @WebParam(name = "dispositivo", targetNamespace = "http://api.cinepolis.com")
        Dispositivos dispositivo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param formato
     * @param idPelicula
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfMultimedia
     */
    @WebMethod(operationName = "ObtenerMultimedia", action = "http://api.cinepolis.com/IConsumo/ObtenerMultimedia")
    @WebResult(name = "ObtenerMultimediaResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerMultimedia", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerMultimedia")
    @ResponseWrapper(localName = "ObtenerMultimediaResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerMultimediaResponse")
    public ArrayOfMultimedia obtenerMultimedia(
        @WebParam(name = "idPelicula", targetNamespace = "http://api.cinepolis.com")
        Integer idPelicula,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param dispositivo
     * @param formato
     * @param idPelicula
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfMultimedia
     */
    @WebMethod(operationName = "ObtenerMultimediaDispositivo", action = "http://api.cinepolis.com/IConsumo/ObtenerMultimediaDispositivo")
    @WebResult(name = "ObtenerMultimediaDispositivoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerMultimediaDispositivo", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerMultimediaDispositivo")
    @ResponseWrapper(localName = "ObtenerMultimediaDispositivoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerMultimediaDispositivoResponse")
    public ArrayOfMultimedia obtenerMultimediaDispositivo(
        @WebParam(name = "idPelicula", targetNamespace = "http://api.cinepolis.com")
        Integer idPelicula,
        @WebParam(name = "dispositivo", targetNamespace = "http://api.cinepolis.com")
        Dispositivos dispositivo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idsComplejos
     * @param formato
     * @param idsPaises
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfRelacionComplejoPelicula
     */
    @WebMethod(operationName = "ObtenerRelacionesPeliculasComplejos", action = "http://api.cinepolis.com/IConsumo/ObtenerRelacionesPeliculasComplejos")
    @WebResult(name = "ObtenerRelacionesPeliculasComplejosResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerRelacionesPeliculasComplejos", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerRelacionesPeliculasComplejos")
    @ResponseWrapper(localName = "ObtenerRelacionesPeliculasComplejosResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerRelacionesPeliculasComplejosResponse")
    public ArrayOfRelacionComplejoPelicula obtenerRelacionesPeliculasComplejos(
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "idsPaises", targetNamespace = "http://api.cinepolis.com")
        String idsPaises,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idsComplejos
     * @param formato
     * @param idPelicula
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfHorariosPelicula
     */
    @WebMethod(operationName = "ObtenerHorariosPelicula", action = "http://api.cinepolis.com/IConsumo/ObtenerHorariosPelicula")
    @WebResult(name = "ObtenerHorariosPeliculaResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerHorariosPelicula", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosPelicula")
    @ResponseWrapper(localName = "ObtenerHorariosPeliculaResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosPeliculaResponse")
    public ArrayOfHorariosPelicula obtenerHorariosPelicula(
        @WebParam(name = "idPelicula", targetNamespace = "http://api.cinepolis.com")
        Integer idPelicula,
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param margenTiempo
     * @param idsComplejos
     * @param formato
     * @param idPelicula
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfHorariosPelicula
     */
    @WebMethod(operationName = "ObtenerHorariosPeliculaMargenTiempo", action = "http://api.cinepolis.com/IConsumo/ObtenerHorariosPeliculaMargenTiempo")
    @WebResult(name = "ObtenerHorariosPeliculaMargenTiempoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerHorariosPeliculaMargenTiempo", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosPeliculaMargenTiempo")
    @ResponseWrapper(localName = "ObtenerHorariosPeliculaMargenTiempoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosPeliculaMargenTiempoResponse")
    public ArrayOfHorariosPelicula obtenerHorariosPeliculaMargenTiempo(
        @WebParam(name = "idPelicula", targetNamespace = "http://api.cinepolis.com")
        Integer idPelicula,
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "margenTiempo", targetNamespace = "http://api.cinepolis.com")
        Integer margenTiempo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idsComplejos
     * @param formato
     * @param idsPaises
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfHorariosPeliculaHorariosComplejoNokia
     */
    @WebMethod(operationName = "ObtenerHorariosComplejo", action = "http://api.cinepolis.com/IConsumo/ObtenerHorariosComplejo")
    @WebResult(name = "ObtenerHorariosComplejoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerHorariosComplejo", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosComplejo")
    @ResponseWrapper(localName = "ObtenerHorariosComplejoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosComplejoResponse")
    public ArrayOfHorariosPeliculaHorariosComplejoNokia obtenerHorariosComplejo(
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "idsPaises", targetNamespace = "http://api.cinepolis.com")
        String idsPaises,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param margenTiempo
     * @param idsComplejos
     * @param formato
     * @param idsPaises
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfHorariosPeliculaHorariosComplejoNokia
     */
    @WebMethod(operationName = "ObtenerHorariosComplejoMargenTiempo", action = "http://api.cinepolis.com/IConsumo/ObtenerHorariosComplejoMargenTiempo")
    @WebResult(name = "ObtenerHorariosComplejoMargenTiempoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerHorariosComplejoMargenTiempo", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosComplejoMargenTiempo")
    @ResponseWrapper(localName = "ObtenerHorariosComplejoMargenTiempoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosComplejoMargenTiempoResponse")
    public ArrayOfHorariosPeliculaHorariosComplejoNokia obtenerHorariosComplejoMargenTiempo(
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "idsPaises", targetNamespace = "http://api.cinepolis.com")
        String idsPaises,
        @WebParam(name = "margenTiempo", targetNamespace = "http://api.cinepolis.com")
        Integer margenTiempo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idPais
     * @param idsComplejos
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfTipoHorarioFiltro
     */
    @WebMethod(operationName = "ObtenerHorariosFiltro", action = "http://api.cinepolis.com/IConsumo/ObtenerHorariosFiltro")
    @WebResult(name = "ObtenerHorariosFiltroResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerHorariosFiltro", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosFiltro")
    @ResponseWrapper(localName = "ObtenerHorariosFiltroResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosFiltroResponse")
    public ArrayOfTipoHorarioFiltro obtenerHorariosFiltro(
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        Integer idPais,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param margenTiempo
     * @param idPais
     * @param idsComplejos
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfTipoHorarioFiltro
     */
    @WebMethod(operationName = "ObtenerHorariosFiltroMargenTiempo", action = "http://api.cinepolis.com/IConsumo/ObtenerHorariosFiltroMargenTiempo")
    @WebResult(name = "ObtenerHorariosFiltroMargenTiempoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerHorariosFiltroMargenTiempo", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosFiltroMargenTiempo")
    @ResponseWrapper(localName = "ObtenerHorariosFiltroMargenTiempoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerHorariosFiltroMargenTiempoResponse")
    public ArrayOfTipoHorarioFiltro obtenerHorariosFiltroMargenTiempo(
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        Integer idPais,
        @WebParam(name = "margenTiempo", targetNamespace = "http://api.cinepolis.com")
        Integer margenTiempo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPromocion
     */
    @WebMethod(operationName = "ObtenerPromociones", action = "http://api.cinepolis.com/IConsumo/ObtenerPromociones")
    @WebResult(name = "ObtenerPromocionesResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPromociones", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPromociones")
    @ResponseWrapper(localName = "ObtenerPromocionesResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPromocionesResponse")
    public ArrayOfPromocion obtenerPromociones(
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idPais
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPromocion
     */
    @WebMethod(operationName = "ObtenerPromocionesFront", action = "http://api.cinepolis.com/IConsumo/ObtenerPromocionesFront")
    @WebResult(name = "ObtenerPromocionesFrontResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPromocionesFront", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPromocionesFront")
    @ResponseWrapper(localName = "ObtenerPromocionesFrontResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPromocionesFrontResponse")
    public ArrayOfPromocion obtenerPromocionesFront(
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato,
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        Integer idPais);

    /**
     * 
     * @param formato
     * @param idComplejo
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfPromocionMoviles
     */
    @WebMethod(operationName = "ObtenerPromocionesMoviles", action = "http://api.cinepolis.com/IConsumo/ObtenerPromocionesMoviles")
    @WebResult(name = "ObtenerPromocionesMovilesResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerPromocionesMoviles", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPromocionesMoviles")
    @ResponseWrapper(localName = "ObtenerPromocionesMovilesResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerPromocionesMovilesResponse")
    public ArrayOfPromocionMoviles obtenerPromocionesMoviles(
        @WebParam(name = "idComplejo", targetNamespace = "http://api.cinepolis.com")
        Integer idComplejo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param formato
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "VerificarPromocionLanzamiento", action = "http://api.cinepolis.com/IConsumo/VerificarPromocionLanzamiento")
    @WebResult(name = "VerificarPromocionLanzamientoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "VerificarPromocionLanzamiento", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.VerificarPromocionLanzamiento")
    @ResponseWrapper(localName = "VerificarPromocionLanzamientoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.VerificarPromocionLanzamientoResponse")
    public Boolean verificarPromocionLanzamiento(
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param strIMEI
     * @param formato
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RedencionPromocionLanzamiento", action = "http://api.cinepolis.com/IConsumo/RedencionPromocionLanzamiento")
    @WebResult(name = "RedencionPromocionLanzamientoResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "RedencionPromocionLanzamiento", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.RedencionPromocionLanzamiento")
    @ResponseWrapper(localName = "RedencionPromocionLanzamientoResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.RedencionPromocionLanzamientoResponse")
    public String redencionPromocionLanzamiento(
        @WebParam(name = "strIMEI", targetNamespace = "http://api.cinepolis.com")
        String strIMEI,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param dispositivo
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfRuta
     */
    @WebMethod(operationName = "ObtenerRutas", action = "http://api.cinepolis.com/IConsumo/ObtenerRutas")
    @WebResult(name = "ObtenerRutasResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerRutas", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerRutas")
    @ResponseWrapper(localName = "ObtenerRutasResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerRutasResponse")
    public ArrayOfRuta obtenerRutas(
        @WebParam(name = "dispositivo", targetNamespace = "http://api.cinepolis.com")
        Dispositivos dispositivo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param dispositivo
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfImagenGenerica
     */
    @WebMethod(operationName = "ObtenerImagenesGenericas", action = "http://api.cinepolis.com/IConsumo/ObtenerImagenesGenericas")
    @WebResult(name = "ObtenerImagenesGenericasResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerImagenesGenericas", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerImagenesGenericas")
    @ResponseWrapper(localName = "ObtenerImagenesGenericasResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerImagenesGenericasResponse")
    public ArrayOfImagenGenerica obtenerImagenesGenericas(
        @WebParam(name = "dispositivo", targetNamespace = "http://api.cinepolis.com")
        Dispositivos dispositivo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param dispositivo
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.Version
     */
    @WebMethod(operationName = "ObtenerInformacionVersion", action = "http://api.cinepolis.com/IConsumo/ObtenerInformacionVersion")
    @WebResult(name = "ObtenerInformacionVersionResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerInformacionVersion", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerInformacionVersion")
    @ResponseWrapper(localName = "ObtenerInformacionVersionResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerInformacionVersionResponse")
    public Version obtenerInformacionVersion(
        @WebParam(name = "dispositivo", targetNamespace = "http://api.cinepolis.com")
        Dispositivos dispositivo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idsComplejos
     * @param formato
     * @param idsPaises
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfFestival
     */
    @WebMethod(operationName = "ObtenerFestivales", action = "http://api.cinepolis.com/IConsumo/ObtenerFestivales")
    @WebResult(name = "ObtenerFestivalesResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerFestivales", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerFestivales")
    @ResponseWrapper(localName = "ObtenerFestivalesResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerFestivalesResponse")
    public ArrayOfFestival obtenerFestivales(
        @WebParam(name = "idsComplejos", targetNamespace = "http://api.cinepolis.com")
        String idsComplejos,
        @WebParam(name = "idsPaises", targetNamespace = "http://api.cinepolis.com")
        String idsPaises,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param formato
     * @param idComplejo
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfTarifa
     */
    @WebMethod(operationName = "ObtenerTarifas", action = "http://api.cinepolis.com/IConsumo/ObtenerTarifas")
    @WebResult(name = "ObtenerTarifasResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerTarifas", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerTarifas")
    @ResponseWrapper(localName = "ObtenerTarifasResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerTarifasResponse")
    public ArrayOfTarifa obtenerTarifas(
        @WebParam(name = "idComplejo", targetNamespace = "http://api.cinepolis.com")
        Integer idComplejo,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param idPais
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfEstado
     */
    @WebMethod(operationName = "ObtenerEstados", action = "http://api.cinepolis.com/IConsumo/ObtenerEstados")
    @WebResult(name = "ObtenerEstadosResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerEstados", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerEstados")
    @ResponseWrapper(localName = "ObtenerEstadosResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerEstadosResponse")
    public ArrayOfEstado obtenerEstados(
        @WebParam(name = "idPais", targetNamespace = "http://api.cinepolis.com")
        Integer idPais,
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

    /**
     * 
     * @param formato
     * @return
     *     returns org.datacontract.schemas._2004._07.apicinepolis.ArrayOfDistribuidora
     */
    @WebMethod(operationName = "ObtenerDistribuidoras", action = "http://api.cinepolis.com/IConsumo/ObtenerDistribuidoras")
    @WebResult(name = "ObtenerDistribuidorasResult", targetNamespace = "http://api.cinepolis.com")
    @RequestWrapper(localName = "ObtenerDistribuidoras", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerDistribuidoras")
    @ResponseWrapper(localName = "ObtenerDistribuidorasResponse", targetNamespace = "http://api.cinepolis.com", className = "com.cinepolis.api.ObtenerDistribuidorasResponse")
    public ArrayOfDistribuidora obtenerDistribuidoras(
        @WebParam(name = "formato", targetNamespace = "http://api.cinepolis.com")
        String formato);

}
