package mx.com.cinepolis.digital.booking.commons.constants;

public enum Configuration
{
  EMAIL_FROM("EMAIL_FROM"), EMAIL_HOST("EMAIL_HOST"), EMAIL_USER("EMAIL_USER"), EMAIL_PASSWORD("EMAIL_PASSWORD"), EMAIL_PORT(
      "EMAIL_PORT"), EMAIL_BOOKING_THEATER_BODY("EMAIL_BOOKING_THEATER_BODY"), EMAIL_BOOKING_THEATER_SUBJECT(
      "EMAIL_BOOKING_THEATER_SUBJECT"), EMAIL_BOOKING_THEATER_BCC("EMAIL_BOOKING_THEATER_BCC"), EMAIL_BOOKING_REGION_BODY(
      "EMAIL_BOOKING_REGION_BODY"), EMAIL_BOOKING_REGION_SUBJECT("EMAIL_BOOKING_REGION_SUBJECT"), EMAIL_BOOKING_REGION_BCC(
      "EMAIL_BOOKING_REGION_BCC"), CURRENT_WEEK_DAYS_OFFSET("currentWeekDaysOffset"), ACTIVE_DIRECTORY_LDAP_URL(
      "ldapUrl"), ACTIVE_DIRECTORY_LDAP_AUTH_METHOD("ldapAuthMethod"), ACTIVE_DIRECTORY_LDAP_DN("ldapDn"), ACTIVE_DIRECTORY_LDAP_PW(
      "ldapPw"), ACTIVE_DIRECTORY_LDAP_VERSION("ldapVersion"), ACTIVE_DIRECTORY_LDAP_AT("ldapAt"), ACTIVE_DIRECTORY_LDAP_TRUST_STORE(
      "ldapTrustStore"), ACTIVE_DIRECTORY_USE_SSL("ldapUseSSL"), WEEK_TOP_MOVIES("WEEK_TOP_MOVIES"), WEEK_START_DAY(
      "WEEK_START_DAY"), WEEK_FINAL_DAY("WEEK_FINAL_DAY"), NUM_WEEKS_OF_YEAR("NUM_WEEKS_OF_YEAR"), ID_COUNTRY_MX(
      "ID_COUNTRY_MX"), ID_CATEGORY_MOVIE_SOUND("ID_CATEGORY_MOVIE_SOUND"), ID_CATEGORY_MOVIE_FORMAT(
      "ID_CATEGORY_MOVIE_FORMAT"), SCHEDULE_EVENT_MOVIES("SCHEDULE_EVENT_MOVIES"), SCHEDULE_DISTRIBUTORS(
      "SCHEDULE_DISTRIBUTORS"), SCHEDULE_COUNTRYS("SCHEDULE_COUNTRYS"), SCHEDULE_CITIES("SCHEDULE_CITIES"), SCHEDULE_ESTATES(
      "SCHEDULE_ESTATES"), SCHEDULE_THEATERS("SCHEDULE_THEATERS"), ID_DEFAULT_DISTRIBUTOR("ID_DEFAULT_DISTRIBUTOR"), EDITABLE_DAYS(
      "EDITABLE_DAYS"), THEATERS_ALLOWED_DUPLICATE_ID_VISTA("THEATERS_ALLOWED_DUPLICATE_ID_VISTA"), ID_DISTRIBUTOR_ALTERNATIVE_CONTENT(
      "ID_DISTRIBUTOR_ALTERNATIVE_CONTENT"), SCHEDULE_DEACTIVATE_PRESALES("SCHEDULE_DEACTIVATE_PRESALES");
  /**
   * Paramter
   */
  private String parameter;

  private Configuration( String parameter )
  {
    this.parameter = parameter;
  }

  /**
   * Gets the parameter associated with the enumeration
   * 
   * @return
   */
  public String getParameter()
  {
    return parameter;
  }

}
